### ISSUE TITLE
Content width not set properly

### ISSUE THREAD

**Issue by barnumbirr** [laymonage/giscus#170]
Even though default styles were defined in [PR#102](https://github.com/laymonage/giscus/pull/102), I'm still experiencing width setting issues:

![Capture](https://user-images.githubusercontent.com/2029239/133475736-07c846a4-5273-4ac2-adbe-cd56ae1c8e92.PNG)

Both rules added in that PR are set properly in the inline stylesheet but `.gsc-comments` is still missing 1 or 2 pixels worth of `padding-right`. [Here's a live demo](https://wiki.martinsimon.me/hardware/TS873A/) if you need to give it a spin yourself.

Thanks 💪

**Comment by laymonage** [comment]
@barnumbirr Looks just fine on my end. What browser are you using? Have you tried disabling all browser extensions (e.g. try opening in an incognito/private window)?

![Screenshot from 2021-09-16 06-23-39](https://user-images.githubusercontent.com/6379424/133525765-13115e1d-1aeb-4f33-a886-f99b570a95ec.png)

**Comment by laymonage** [comment]
@barnumbirr The issue seems to come from your end. The left/right margin in this rule is too large:

![image](https://user-images.githubusercontent.com/6379424/133527084-df102540-6f43-4a27-8a37-dad25ab3036a.png)

Disabling them or reducing the value (e.g. to 1.1rem) seems to fix it.

**Comment by barnumbirr** [comment]
@laymonage thank you for looking into the issue. I'm using Firefox 92.0 but haven't touched left margins. The only CSS I've modified is to reverse the comment box and comments order as follows:

```css
.gsc-comments > .gsc-header {
  order: 1;
}

.gsc-comments > .gsc-comment-box {
  order: 2;
  margin-bottom: 1rem;
}

.gsc-comments > .gsc-timeline {
  order: 3;
}

.gsc-timeline {
  flex-direction: column-reverse;
}

.gsc-header {
  padding-bottom: 1rem;
}
```

**Comment by laymonage** [comment]
@barnumbirr Yes, but the issue comes from the your MkDocs theme's CSS, specifically the rules I pointed above. You can see that it works just fine on [my website](https://laymonage.com/posts/giscus) and https://giscus.app itself. You need to modify your MkDocs' theme. You can also add something like the following to your custom CSS for giscus, but to be honest this feels like a hack:

```css
.gsc-comments {
  padding-right: 1px;
}
```

**Comment by barnumbirr** [comment]
@laymonage although adding one pixel of right padding to the `gsc-comments` class feels like a hack, I fell more comfortable with that then modifying Material for MkDocs' CSS. Unfortunately, that padding doesn't seem to fix it and I still can't wrap my head around why Material for MkDocs would break it in the first place as adding any value other than `1.2rem` to `margin-right` as you've pointed out above seems to work just fine.

**Comment by laymonage** [comment]
@barnumbirr You're not supposed to put the custom CSS on your website. The widget is loaded in an `<iframe>` so your styles won't have any effect. You need to use a custom giscus theme via the [`data-theme`](https://github.com/laymonage/giscus/blob/main/ADVANCED-USAGE.md#data-theme) attribute.

If that's too much hassle for you, try this instead:

```css
.md-main .md-content > .md-content__inner.md-typeset {
    margin-left: 1.1rem;
    margin-right: 1.1rem;
}
```

It's probably a bug in either the Material MkDocs or Firefox, maybe you could open an issue there.
