### ISSUE TITLE
The width is not correctly resized

### ISSUE THREAD

**Issue by vaparo** [laymonage/giscus#90]
Example: https://vaparo.github.io/about/

The comment widget has default width and border style.

**Comment by laymonage** [comment]
@vaparo Have you followed the CSS example?

```css
.giscus, .giscus-frame {
  width: 100%;
}

.giscus-frame {
  border: none;
}
```
